#!/usr/bin/env bash
set -euo pipefail

# snapshot_schema.sh
# ---------------------------------------------------------------------------
# Creates a DATA-FREE schema snapshot of the database and writes it to
# db-schema.sql at the repository root. Commit db-schema.sql to git so schema
# changes travel with the code. On a previously deployed site, run
# scripts/sync_schema.sh to bring that site's database up to the snapshot.
#
# Usage:
#   ./scripts/snapshot_schema.sh            # uses .env DATABASE_URL
#   DATABASE_URL=postgres://u:p@h:5432/db ./scripts/snapshot_schema.sh
#   PGHOST=localhost PGUSER=u PGPASSWORD=p PGDATABASE=db ./scripts/snapshot_schema.sh
# Requires: pg_dump, psql
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_FILE="$REPO_ROOT/db-schema.sql"

if [ -z "${DATABASE_URL:-}" ] && [ -f "$REPO_ROOT/.env" ]; then
  DATABASE_URL=$(grep -E '^DATABASE_URL=' "$REPO_ROOT/.env" | head -1 | cut -d= -f2-)
fi

parse_url() {
  local url="$1"
  local rest="$url"
  rest="${rest#postgres://}"
  rest="${rest#postgresql://}"
  local creds="${rest%%@*}"
  local hostportdb="${rest#*@}"
  PGUSER="${creds%%:*}"
  PGPASSWORD="${creds#*:}"; PGPASSWORD="${PGPASSWORD%%@*}"
  if [[ "$hostportdb" == *:*/* ]]; then
    PGHOST="${hostportdb%%:*}"
    PGDATABASE="${hostportdb#*:}"; PGDATABASE="${PGDATABASE#*/}"
  elif [[ "$hostportdb" == */* ]]; then
    PGHOST="${hostportdb%%/*}"; PGDATABASE="${hostportdb#*/}"
  else
    PGHOST="localhost"; PGDATABASE="$hostportdb"
  fi
  export PGUSER PGPASSWORD PGHOST PGDATABASE
}

if [ -n "${DATABASE_URL:-}" ]; then
  parse_url "$DATABASE_URL"
elif [ -z "${PGDATABASE:-}" ]; then
  echo "Error: set DATABASE_URL or PG* env vars." >&2; exit 1
fi
PGHOST="${PGHOST:-localhost}"; PGPORT="${PGPORT:-5432}"

if ! command -v pg_dump >/dev/null 2>&1; then
  echo "Error: pg_dump not found." >&2; exit 1
fi

echo "== Schema snapshot =="
echo "   Host: $PGHOST:$PGPORT   Database: $PGDATABASE"
echo "   Output: $OUT_FILE"; echo

if ! pg_dump --schema-only --no-owner --no-privileges --no-comments \
             -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" \
             > "$OUT_FILE.tmp"; then
  echo "Error: pg_dump failed." >&2; rm -f "$OUT_FILE.tmp"; exit 1
fi

{
  echo "-- Krewe Mystique - database schema snapshot (DATA-FREE)."
  echo "-- Generated by scripts/snapshot_schema.sh (pg_dump --schema-only)."
  echo "-- Apply to a deployed site with: ./scripts/sync_schema.sh"
  echo "--"
  cat "$OUT_FILE.tmp"
} > "$OUT_FILE"
rm -f "$OUT_FILE.tmp"

echo "Done. Schema written to db-schema.sql."
echo "Review the diff, then: git add db-schema.sql && git commit -m 'chore: update db schema snapshot'"
