#!/usr/bin/env bash
set -euo pipefail

# sync_schema.sh
# ---------------------------------------------------------------------------
# Brings a DEPLOYED site's database schema up to date with the committed
# snapshot (db-schema.sql) - WITHOUT touching or deleting any data.
#
# Idempotent: rewrites the snapshot so existing objects are skipped
# (IF NOT EXISTS / CREATE OR REPLACE / guarded constraint adds). Never
# issues DROP. Safe to re-run after every code pull.
#
# Does NOT: drop missing objects, rename, or alter column types.
# (Those need a one-off manual migration.)
#
# Usage:
#   ./scripts/sync_schema.sh              # uses .env DATABASE_URL
#   DATABASE_URL=postgres://u:p@h:5432/db ./scripts/sync_schema.sh
#   PGHOST=localhost PGUSER=u PGPASSWORD=p PGDATABASE=db ./scripts/sync_schema.sh
# Requires: psql
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCHEMA_FILE="$REPO_ROOT/db-schema.sql"

if [ ! -f "$SCHEMA_FILE" ]; then
  echo "Error: $SCHEMA_FILE not found." >&2
  echo "       Run ./scripts/snapshot_schema.sh first." >&2; exit 1
fi

if [ -z "${DATABASE_URL:-}" ] && [ -f "$REPO_ROOT/.env" ]; then
  DATABASE_URL=$(grep -E '^DATABASE_URL=' "$REPO_ROOT/.env" | head -1 | cut -d= -f2-)
fi

parse_url() {
  local url="$1"
  local rest="$url"
  rest="${rest#postgres://}"
  rest="${rest#postgresql://}"
  local creds="${rest%%@*}"
  local hostportdb="${rest#*@}"
  PGUSER="${creds%%:*}"
  PGPASSWORD="${creds#*:}"; PGPASSWORD="${PGPASSWORD%%@*}"
  if [[ "$hostportdb" == *:*/* ]]; then
    PGHOST="${hostportdb%%:*}"
    PGDATABASE="${hostportdb#*:}"; PGDATABASE="${PGDATABASE#*/}"
  elif [[ "$hostportdb" == */* ]]; then
    PGHOST="${hostportdb%%/*}"; PGDATABASE="${hostportdb#*/}"
  else
    PGHOST="localhost"; PGDATABASE="$hostportdb"
  fi
  export PGUSER PGPASSWORD PGHOST PGDATABASE
}

if [ -n "${DATABASE_URL:-}" ]; then
  parse_url "$DATABASE_URL"
elif [ -z "${PGDATABASE:-}" ]; then
  echo "Error: set DATABASE_URL or PG* env vars." >&2; exit 1
fi
PGHOST="${PGHOST:-localhost}"; PGPORT="${PGPORT:-5432}"

if ! command -v psql >/dev/null 2>&1; then
  echo "Error: psql not found." >&2; exit 1
fi

if ! PGPASSWORD="$PGPASSWORD" psql -v ON_ERROR_STOP=1 --no-psqlrc \
     -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -c "SELECT 1" >/dev/null 2>&1; then
  echo "Error: cannot connect to $PGHOST:$PGPORT/$PGDATABASE as $PGUSER." >&2; exit 1
fi

echo "== Schema sync =="
echo "   Host: $PGHOST:$PGPORT   Database: $PGDATABASE"
echo "   Source: $SCHEMA_FILE"; echo

IDEMPOTENT_FILE="$(mktemp)"
{
  echo "-- Idempotent schema sync generated by scripts/sync_schema.sh"
  echo "-- Source: db-schema.sql (data-free snapshot). No DROP, no data changes."
  echo "--"
  awk '
    # Drop whole COMMENT ON statements.
    /^COMMENT ON/ { while (getline && $0 !~ /;$/) {}; next }

    # Drop whole CREATE SEQUENCE blocks (the SERIAL column already created them).
    /^CREATE SEQUENCE / { while (getline && $0 !~ /;$/) {}; next }

    # CREATE FUNCTION: make it CREATE OR REPLACE, pass the body through verbatim.
    /^CREATE FUNCTION / || /^CREATE OR REPLACE FUNCTION / {
      sub(/^CREATE FUNCTION /, "CREATE OR REPLACE FUNCTION ")
      print
      while (getline && $0 !~ /END[[:space:]]*\$\$;?$/) { print }
      print
      next
    }

    # ALTER TABLE ONLY ... header (constraint or column default on following line).
    /^ALTER TABLE ONLY [^ ]+/ && !/ADD/ {
      hdr = $0
      getline nl
      if (nl ~ /ADD CONSTRAINT [^ ]+ PRIMARY KEY/) { next }          # redundant PK
      if (nl ~ /ADD CONSTRAINT [^ ]+ /) {                            # FK/UNIQUE/CHECK
        rest = nl
        sub(/^[[:space:]]*ADD CONSTRAINT /, "", rest)
        cname = rest; sub(/ .*$/, "", cname)
        n = split(hdr, p, " "); tbl = p[4]
        print "DO $$"
        print "BEGIN"
        print "  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '"'"'" cname "'"'"' AND conrelid = '"'"'" tbl "'"'"'::regclass) THEN"
        print "    " hdr " " rest
        print "  END IF;"
        print "END $$;"
        next
      }
      # Otherwise a self-contained ALTER (e.g. ALTER COLUMN ... SET DEFAULT).
      print hdr; print nl
      next
    }

    /^CREATE TABLE / { sub(/^CREATE TABLE /, "CREATE TABLE IF NOT EXISTS "); print; next }
    /^CREATE INDEX / { sub(/^CREATE INDEX /, "CREATE INDEX IF NOT EXISTS "); print; next }
    /^CREATE UNIQUE INDEX / { sub(/^CREATE UNIQUE INDEX /, "CREATE UNIQUE INDEX IF NOT EXISTS "); print; next }
    /^CREATE INDEX CONCURRENTLY / { sub(/^CREATE INDEX CONCURRENTLY /, "CREATE INDEX CONCURRENTLY IF NOT EXISTS "); print; next }
    /ALTER TABLE [^ ]+ ADD COLUMN/ { sub(/ADD COLUMN /, "ADD COLUMN IF NOT EXISTS "); print; next }
    { print }
  ' "$SCHEMA_FILE"
} > "$IDEMPOTENT_FILE"

# Apply. ON_ERROR_STOP=0 so benign "already exists" errors are skipped.
PSQL_OUT="$(mktemp)"
if ! PGPASSWORD="$PGPASSWORD" psql -v ON_ERROR_STOP=0 --no-psqlrc \
     -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" \
     -f "$IDEMPOTENT_FILE" 2>&1 | tee "$PSQL_OUT"; then
  echo "Error: schema apply reported a failure." >&2; rm -f "$IDEMPOTENT_FILE" "$PSQL_OUT"; exit 1
fi

echo
UNEXPECTED=$(grep -iE 'ERROR' "$PSQL_OUT" | grep -viE 'already exists|does not exist' || true)
if [ -n "$UNEXPECTED" ]; then
  echo "WARNING: unexpected errors during apply (review above):"
  echo "$UNEXPECTED"
else
  echo "No unexpected errors. (Any 'already exists' lines are expected on a"
  echo "database that already matches the snapshot - they are safely ignored.)"
fi
rm -f "$IDEMPOTENT_FILE" "$PSQL_OUT"

echo; echo "Done. Schema is now in sync with db-schema.sql."
echo "No data was modified. Re-run any time after pulling code changes."
