#!/usr/bin/env bash
set -euo pipefail

# sync_schema.sh
# ---------------------------------------------------------------------------
# Brings a DEPLOYED site's database schema up to date with the committed
# snapshot (db-schema.sql) - WITHOUT touching or deleting any data.
#
# Idempotent and SELF-UPDATING: the rewrites are driven generically by
# statement keyword - CREATE TABLE / SEQUENCE / INDEX / FUNCTION /
# PROCEDURE / VIEW / EXTENSION become IF NOT EXISTS or CREATE OR REPLACE;
# ALTER TABLE ... ADD CONSTRAINT becomes a guarded DO block. There are NO
# hard-coded assumptions about how the schema is laid out, so adding
# tables, columns, constraints, sequences, indexes, functions, views, or
# extensions NEVER requires editing this script. It behaves identically on
# an empty, partially-migrated, or fully-synced target, then VERIFIES the
# result (every snapshot table and default-referenced sequence must exist).
#
# Never issues DROP. Safe to re-run after every code pull.
#
# Does NOT: drop missing objects, rename, or alter column types.
# (Those need a one-off manual migration.)
#
# Usage:
#   ./scripts/sync_schema.sh              # uses .env DATABASE_URL
#   DATABASE_URL=postgres://u:p@h:5432/db ./scripts/sync_schema.sh
#   PGHOST=localhost PGUSER=u PGPASSWORD=p PGDATABASE=db ./scripts/sync_schema.sh
# Requires: psql
# ---------------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCHEMA_FILE="$REPO_ROOT/db-schema.sql"

if [ ! -f "$SCHEMA_FILE" ]; then
  echo "Error: $SCHEMA_FILE not found." >&2
  echo "       Run ./scripts/snapshot_schema.sh first." >&2; exit 1
fi

if [ -z "${DATABASE_URL:-}" ] && [ -f "$REPO_ROOT/.env" ]; then
  DATABASE_URL=$(grep -E '^DATABASE_URL=' "$REPO_ROOT/.env" | head -1 | cut -d= -f2-)
fi

parse_url() {
  local url="$1"
  local rest="$url"
  rest="${rest#postgres://}"
  rest="${rest#postgresql://}"
  local creds="${rest%%@*}"
  local hostportdb="${rest#*@}"
  PGUSER="${creds%%:*}"
  PGPASSWORD="${creds#*:}"; PGPASSWORD="${PGPASSWORD%%@*}"
  if [[ "$hostportdb" == *:*/* ]]; then
    PGHOST="${hostportdb%%:*}"
    PGDATABASE="${hostportdb#*:}"; PGDATABASE="${PGDATABASE#*/}"
  elif [[ "$hostportdb" == */* ]]; then
    PGHOST="${hostportdb%%/*}"; PGDATABASE="${hostportdb#*/}"
  else
    PGHOST="localhost"; PGDATABASE="$hostportdb"
  fi
  export PGUSER PGPASSWORD PGHOST PGDATABASE
}

if [ -n "${DATABASE_URL:-}" ]; then
  parse_url "$DATABASE_URL"
elif [ -z "${PGDATABASE:-}" ]; then
  echo "Error: set DATABASE_URL or PG* env vars." >&2; exit 1
fi
PGHOST="${PGHOST:-localhost}"; PGPORT="${PGPORT:-5432}"

if ! command -v psql >/dev/null 2>&1; then
  echo "Error: psql not found." >&2; exit 1
fi

if ! PGPASSWORD="$PGPASSWORD" psql -v ON_ERROR_STOP=1 --no-psqlrc \
     -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" -c "SELECT 1" >/dev/null 2>&1; then
  echo "Error: cannot connect to $PGHOST:$PGPORT/$PGDATABASE as $PGUSER." >&2; exit 1
fi

echo "== Schema sync =="
echo "   Host: $PGHOST:$PGPORT   Database: $PGDATABASE"
echo "   Source: $SCHEMA_FILE"; echo

IDEMPOTENT_FILE="$(mktemp)"
{
  echo "-- Idempotent schema sync generated by scripts/sync_schema.sh"
  echo "-- Source: db-schema.sql (data-free snapshot). No DROP, no data changes."
  echo "--"
  awk '
    # psql backslash meta-commands (e.g. \restrict, \unrestrict, \connect).
    # pg_dump (v16+) emits \restrict / \unrestrict; they are client-only and
    # would error on older psql. Strip ANY line that is a psql backslash
    # command so the dump is portable and applies cleanly everywhere. This is
    # generic - it does not name specific commands, so new pg_dump output is
    # handled automatically.
    /^\\[[:alpha:]]/ { next }

    # Drop whole COMMENT ON statements.
    /^COMMENT ON/ { if ($0 !~ /;$/) { while (getline && $0 !~ /;$/) {} } next }

    # CREATE SEQUENCE: keep and make idempotent. The id columns are plain
    # `integer NOT NULL` with a SEPARATE sequence that is wired up via
    # ALTER COLUMN ... SET DEFAULT nextval(...). pg_dump never inlines these,
    # so the sequence MUST be created. (Dropping this block - the original
    # bug - broke the SET DEFAULT statements with "relation ..._id_seq does
    # not exist".) Handled generically for ANY sequence, so adding new
    # serial/id columns never requires touching this script.
    /^CREATE SEQUENCE / {
      sub(/^CREATE SEQUENCE /, "CREATE SEQUENCE IF NOT EXISTS ")
      print
      next
    }

    # CREATE FUNCTION / PROCEDURE: make it CREATE OR REPLACE, pass the body
    # through verbatim. Idempotent for any function/procedure.
    /^CREATE( OR REPLACE)? (FUNCTION|PROCEDURE) / {
      sub(/^CREATE FUNCTION /, "CREATE OR REPLACE FUNCTION ")
      sub(/^CREATE PROCEDURE /, "CREATE OR REPLACE PROCEDURE ")
      print
      while (getline && $0 !~ /^[[:space:]]*\$\$/ && $0 !~ /^[[:space:]]*\$[A-Za-z_]*\$;?$/) { print }
      print
      next
    }

    # CREATE VIEW / MATERIALIZED VIEW: idempotent replace. Covers views that
    # may be added to the schema later without editing this script.
    /^CREATE VIEW / { sub(/^CREATE VIEW /, "CREATE OR REPLACE VIEW "); print; next }
    /^CREATE MATERIALIZED VIEW / { sub(/^CREATE MATERIALIZED VIEW /, "CREATE OR REPLACE MATERIALIZED VIEW "); print; next }

    # ALTER TABLE ... header (a constraint or a column default on the next
    # line). Buffer it; if the following line is ADD CONSTRAINT, emit an
    # idempotent guarded DO block. Otherwise (e.g. ALTER COLUMN ... SET
    # DEFAULT) emit the line unchanged. Handles BOTH "ALTER TABLE ONLY x"
    # and "ALTER TABLE x" so it is robust to pg_dump output format and
    # needs no edits when the schema changes.
    /^ALTER TABLE( ONLY)? [^ ]+/ && !/ADD/ {
        if (pendingAlter != "") { print pendingAlter }
        pendingAlter = $0
        n = split(pendingAlter, p, " ")
        curTbl = (p[3] == "ONLY") ? p[4] : p[3]
        next
    }
    pendingAlter != "" && /^[[:space:]]*ADD CONSTRAINT/ {
        rest = $0
        sub(/^[[:space:]]*ADD CONSTRAINT /, "", rest)
        cname = rest; sub(/ .*$/, "", cname)
        print "DO $$"
        print "BEGIN"
        print "  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = '"'"'" cname "'"'"' AND conrelid = '"'"'" curTbl "'"'"'::regclass) THEN"
        print "    " pendingAlter " ADD CONSTRAINT " rest
        print "  END IF;"
        print "END $$;"
        pendingAlter = ""
        next
    }
    pendingAlter != "" {
        # Header seen but the next line was not an ADD CONSTRAINT (defensive).
        print pendingAlter
        pendingAlter = ""
    }

    # Simple, generic keyword idempotency swaps (first line of each statement).
    # Covers every statement type pg_dump emits for typical schema objects;
    # new tables / columns / indexes / extensions added later are handled
    # automatically (no script edits needed). CREATE INDEX CONCURRENTLY is
    # checked before plain CREATE INDEX so the word CONCURRENTLY is preserved.
    /^CREATE TABLE /              { sub(/^CREATE TABLE /,              "CREATE TABLE IF NOT EXISTS ");              print; next }
    /^CREATE UNIQUE INDEX /      { sub(/^CREATE UNIQUE INDEX /,      "CREATE UNIQUE INDEX IF NOT EXISTS ");      print; next }
    /^CREATE INDEX CONCURRENTLY / { sub(/^CREATE INDEX CONCURRENTLY /, "CREATE INDEX CONCURRENTLY IF NOT EXISTS "); print; next }
    /^CREATE INDEX /             { sub(/^CREATE INDEX /,             "CREATE INDEX IF NOT EXISTS ");             print; next }
    /^CREATE EXTENSION /          { sub(/^CREATE EXTENSION /,          "CREATE EXTENSION IF NOT EXISTS ");          print; next }
    /ALTER TABLE [^ ]+ ADD COLUMN/ { sub(/ADD COLUMN /, "ADD COLUMN IF NOT EXISTS "); print; next }
    END { if (pendingAlter != "") { print pendingAlter } }
    { print }
  ' "$SCHEMA_FILE"
} > "$IDEMPOTENT_FILE"

# Apply. ON_ERROR_STOP=0 lets benign "already exists" errors pass; we
# classify them afterwards and verify the result, so real problems are
# never hidden regardless of the target database's starting state.
PSQL_OUT="$(mktemp)"
if ! PGPASSWORD="$PGPASSWORD" psql -v ON_ERROR_STOP=0 --no-psqlrc \
     -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" \
     -f "$IDEMPOTENT_FILE" 2>&1 | tee "$PSQL_OUT"; then
  echo "Error: schema apply reported a failure." >&2; rm -f "$IDEMPOTENT_FILE" "$PSQL_OUT"; exit 1
fi
rm -f "$IDEMPOTENT_FILE"

echo
# This script never issues DROP, so any "does not exist" error means a real
# missing dependency. Only "already exists" is benign (idempotent re-run on a
# database that already matches the snapshot).
UNEXPECTED=$(grep -iE 'ERROR' "$PSQL_OUT" | grep -viE 'already exists' || true)
if [ -n "$UNEXPECTED" ]; then
  echo "WARNING: unexpected errors during apply (review above):"
  echo "$UNEXPECTED"
else
  echo "No unexpected errors. (Any 'already exists' lines are expected on a"
  echo "database that already matches the snapshot - they are safely ignored.)"
fi

# ---------------------------------------------------------------------------
# Verification: confirm the snapshot's objects actually exist in the target now.
# This catches the class of bug where a transform silently fails (e.g. a
# sequence referenced by a column default was never created). The script never
# reports success unless the schema is genuinely in place - on an empty,
# partially migrated, or already-synced database alike.
# ---------------------------------------------------------------------------
echo "== Verifying applied schema against snapshot =="
verify_failed=0

# Every table declared in the snapshot must now exist in the target.
while IFS= read -r t; do
  [ -z "$t" ] && continue
  if ! PGPASSWORD="$PGPASSWORD" psql -tAc \
       "SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = 'r' AND (n.nspname || '.' || c.relname) = '$t'" \
       -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" | grep -q 1; then
    echo "ERROR: expected table '$t' is missing after sync." >&2
    verify_failed=1
  fi
done < <(grep -oE '^CREATE TABLE [a-zA-Z_]+\.[a-zA-Z_]+' "$SCHEMA_FILE" | awk '{print $3}')

# Every sequence referenced by a column default must now exist.
while IFS= read -r s; do
  [ -z "$s" ] && continue
  if ! PGPASSWORD="$PGPASSWORD" psql -tAc \
       "SELECT 1 FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE c.relkind = 'S' AND (n.nspname || '.' || c.relname) = '$s'" \
       -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE" | grep -q 1; then
    echo "ERROR: expected sequence '$s' (referenced by a column default) is missing after sync." >&2
    verify_failed=1
  fi
done < <(grep -oE "nextval\('[a-zA-Z_]+\.[a-zA-Z_]+'::regclass\)" "$SCHEMA_FILE" | sed -E "s/^nextval\('//; s/'::regclass\)$//" | sort -u)

if [ "$verify_failed" -eq 1 ]; then
  echo "Schema verification FAILED - the target database is incomplete." >&2
  rm -f "$PSQL_OUT"; exit 1
fi
echo "Verification passed: all snapshot tables and referenced sequences exist."
rm -f "$PSQL_OUT"

echo; echo "Done. Schema is now in sync with db-schema.sql."
echo "No data was modified. Re-run any time after pulling code changes."
